ARCHETYPE_PARAMS: dict[str, dict] = {
    "good": {
        "utilization_mean": 0.45,
        "utilization_std": 0.07,
        "utilization_min": 0.30,
        "utilization_max": 0.60,
        "payment_factor_min": 0.92,
        "payment_factor_max": 1.05,
        "income_std": 0.03,
        "income_growth_min": 0.002,
        "income_growth_max": 0.008,
        "default_prob": 0.0,
        "shock_prob": 0.02,
        "transactions_min": 8,
        "transactions_max": 16,
        "transaction_vol_min": 0.05,
        "transaction_vol_max": 0.15,
    },
    "recurrent": {
        "utilization_mean": 0.72,
        "utilization_std": 0.08,
        "utilization_min": 0.60,
        "utilization_max": 0.85,
        "payment_factor_min": 0.55,
        "payment_factor_max": 0.95,
        "income_std": 0.08,
        "income_growth_min": 0.0,
        "income_growth_max": 0.0,
        "default_prob": 0,
        "shock_prob": 0.02,
        "transactions_min": 4,
        "transactions_max": 13,
        "transaction_vol_min": 0.2,
        "transaction_vol_max": 0.4,
    },
    "over": {
        "utilization_mean": 0.96,
        "utilization_std": 0.02,
        "utilization_min": 0.90,
        "utilization_max": 1.00,
        "payment_factor_min": 0.02,
        "payment_factor_max": 0.08,
        "income_std": 0.05,
        "income_growth_min": -0.05,
        "income_growth_max": 0.03,
        "default_prob": 0.7,
        "shock_prob": 0.15,
        "transactions_min": 2,
        "transactions_max": 9,
        "transaction_vol_min": 0.4,
        "transaction_vol_max": 0.7,
        "income_decay_min": 0.04,
        "income_decay_max": 0.07,
    },
    "fraud": {
        "utilization_mean": 0.75,
        "utilization_std": 0.05,
        "utilization_min": 0.65,
        "utilization_max": 0.85,
        "payment_factor_min": 0.85,
        "payment_factor_max": 1.00,
        "income_factor_min": 1.8,
        "income_factor_max": 2.5,
        "income_growth_min": 0.00,
        "income_growth_max": 0.00,
        "default_prob": 0.63,
        "shock_prob": 0.2,
        "transactions_min": 0,
        "transactions_max": 21,
        "transaction_vol_min": 0.00,
        "transaction_vol_max": 0.10,
    },
    "low": {
        "utilization_mean": 0.70,
        "utilization_std": 0.30,
        "utilization_min": 0.05,
        "utilization_max": 0.30,
        "payment_factor_min": 0.8,
        "payment_factor_max": 1.1,
        "income_std": 0.04,
        "income_growth_min": 0.00,
        "income_growth_max": 0.00,
        "default_prob": 0.65,
        "shock_prob": 0.05,
        "transactions_min": 0,
        "transactions_max": 4,
        "transaction_vol_min": 0.01,
        "transaction_vol_max": 0.05,
    }
}

ARCHETYPE_COMPOSITION: dict[str, float] = {
    "good": 0.4,
    "recurrent": 0.25,
    "over": 0.20,
    "fraud": 0.05,
    "low": 0.10
}

assert set(ARCHETYPE_PARAMS.keys()) == {"good", "recurrent", "over", "fraud", "low"}
assert abs(sum(ARCHETYPE_COMPOSITION.values()) - 1.0) < 1e-9
